//Pokemon
export const SET_SELECTED_POKEMON = "SET_SELECTED_POKEMON";
export const SET_POKEMONS = "SET_POKEMONS";
export const SET_SELECTED_POKEMON_EVOLUTION = "SET_SELECTED_POKEMON_EVOLUTION";

//Evolution
export const SET_EVOLUTION = "SET_EVOLUTION";
